namespace: naofpa-dev

gateway:
  enabled: true
  image: us-east1-docker.pkg.dev/vllm-sara/vllm-rag-bot/gateway:latest
  replicas: 1
  port: 7862
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

chroma:
  enabled: true
  image: chromadb/chroma:latest
  port: 8000
  storage: 10Gi
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi

# We'll leave these for later
vllm:
  enabled: false

observability:
  prometheus: false
  grafana: false
